name: Build, Test, and Deploy
on:
  push:
    branches:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run linting
        run: |
          ruff check src/ tests/
          ruff format --check src/ tests/
      - name: MyPy
        run: mypy src/

  py310:
    name: Test (Python 3.10)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Run tox job
        run: |
          pip install tox
          tox -e py310
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ github.event.repository.name }}

  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Run tox job
        run: |
          pip install tox
          tox -e docs
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

  docs-deploy:
    needs: docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: node:22
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/_build/html
      - name: Disable jekyll builds
        run: touch docs/_build/html/.nojekyll
      - name: Deploy docs to gh-pages branch
        run: |
          git config user.email "fx-data-platform@mozilla.com"
          git config user.name "GitHub Actions docs-deploy job"
          npm install -g --silent gh-pages@^2.0.0
          gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html