name: Tagged Deploy

on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9]?.[0-9]+' # Calver: YYYY.M.MINOR

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/p/mozanalysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Create the distribution files
        run: python -m build --sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1